#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import platform_qnx_builders

common_qnx = [
    "display_server_qnx.cpp",
    "gl_manager_qnx_egl.cpp",
    "crash_handler_qnx.cpp",
    "os_qnx.cpp",
    "rendering_context_driver_vulkan_screen.cpp"
]

#if env["use_sowrap"]:
#    common_qnx.append("xkbcommon-so_wrap.c")

if env["x11"]:
    common_qnx += SConscript("x11/SCsub")

if env["wayland"]:
    common_qnx += SConscript("wayland/SCsub")

if env["speechd"]:
    common_qnx.append("tts_linux.cpp")
    if env["use_sowrap"]:
        common_qnx.append("speechd-so_wrap.c")

if env["fontconfig"]:
    if env["use_sowrap"]:
        common_qnx.append("fontconfig-so_wrap.c")

if env["udev"]:
    if env["use_sowrap"]:
        common_qnx.append("libudev-so_wrap.c")

if env["dbus"]:
    if env["use_sowrap"]:
        common_qnx.append("dbus-so_wrap.c")

prog = env.add_program("#bin/godot", ["godot_qnx.cpp"] + common_qnx)

if env["debug_symbols"] and env["separate_debug_symbols"]:
    env.AddPostAction(prog, env.Run(platform_qnx_builders.make_debug_qnx))
