#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

source_files = [
    "display_server_qnx.cpp",
    "key_mapping_qnx_screen.cpp",
    "screen_thread.cpp",
]

if env["vulkan"]:
    source_files.append("rendering_context_driver_vulkan_screen.cpp")

if env["opengl3"]:
    source_files.append(["egl_manager_qnx_screen.cpp"])

objects = []

for source_file in source_files:
    objects.append(env.Object(source_file))

Return("objects")
